In [1]:
import numpy as np

In [2]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [3]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [4]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [5]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [6]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [11]:
# Starting at 0, ending at 20, stepping by 2
# 線形シーケンス配列
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
np.random.random((3, 3))

array([[0.97716352, 0.60156288, 0.5720201 ],
       [0.91101556, 0.55777473, 0.10126284],
       [0.15210442, 0.52015165, 0.25538149]])

平均0と標準偏差1の正規分布乱数で3行3列の配列を作る

In [14]:
np.random.normal(0, 1, (3, 3))

array([[-2.47433216,  0.03059494,  0.15791939],
       [ 0.85544607,  1.86569367,  1.18262288],
       [ 1.46774964, -0.99889441,  0.04282372]])

In [15]:
np.random.randint(0, 10, (3, 3))

array([[1, 6, 9],
       [6, 3, 1],
       [8, 6, 4]])

単位行列

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])